[project]
name = "yt2podcast"
version = "0.1.0"
description = "Add a short description here"
authors = ["satanowski <satanowski@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
yt-dlp = ">=2023.12.30,<2023.13"
python = ">=3.12.1,<3.13"
bpython = ">=0.24,<1"
feedparser = ">=6.0.10,<6.1"
toml = ">=0.10.2,<0.11"
loguru = ">=0.7.2,<0.8"
pickledb = ">=0.9.2,<0.10"
jinja2 = ">=3.1.2,<3.2"
mutagen = ">=1.47.0,<1.48"
black = ">=23.12.1,<23.13"
isort = ">=5.13.2,<5.14"

[tasks]
clean = "/bin/rm -f store/*; rm -f feeds.db"
run = "python main.py"
serve = "python -m http.server"
lint = "isort *.py; black *.py"
